### ISSUE TITLE
capacity explorer can't be loaded 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/tfchain_portal#13]
with devnet: https://portal.tfchain.dev.threefold.io/
i installed polkadot extension and created an account
![image](https://user-images.githubusercontent.com/31102305/141275520-dc51e071-61ae-4313-b73a-865e499e503f.png)

but when i try to click on Capacity Explorer got this:
![image](https://user-images.githubusercontent.com/31102305/141275661-4f3c39c7-9ea5-4b4a-90e0-35fb082c5cf0.png)

**Comment by ramezsaeed** [comment]
Working fine with me
