### ISSUE TITLE
Connect open a new tab with wrong link

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/tfchain_portal#17]
## Description
When I click on connect
New tap open with this link: https://github.com/vuetifyjs/vuetify/releases/tag/v2.6.0

## Screenshot
![portalWrongRedirect](https://user-images.githubusercontent.com/11272864/142425169-747b73e2-662d-4c2a-934d-b4fa1b71e437.gif)

**Comment by DylanVerstraete** [comment]
Fix live on devnet
