### ISSUE TITLE
TF Chain Portal - Refresh Gives 404

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfchain_portal#18]
On the [testnet TFChain portal](https://portal.test.grid.tf/), refreshing the page after opening an account leads to a 404. When sending tokens over the bridge, a way is needed to refresh the balance and check if they've arrived.

**Comment by DylanVerstraete** [comment]
Live on devnet

**Comment by DylanVerstraete** [comment]
Fixed on testnet as well
