### ISSUE TITLE
easy way to cancel contracts

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_portal#19]
right now the flow is from the graphql e.g https://graphql.dev.grid.tf/graphql

```
query MyQuery {

  nodeContracts(where: {twinId_eq: 70}) {
    twinId
    contractId
  }
}

```
I get all my contracts and then from polkadot UI I cancel them one by one 

![image](https://user-images.githubusercontent.com/64129/144474262-ab783955-ed4c-403b-be3d-38bdde62f530.png)

Also can be done using the script in grid3_client_ts https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/delete_all_contracts.ts , but needs to be more friendly.

**Comment by DylanVerstraete** [comment]
We did not integrate smart contract module yet, if we want to have this feature I think we also should support contract creation
