### ISSUE TITLE
 change vue favicon to Threefold favicon

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/tfchain_portal#21]
this should be changed ASAP as we are going to announce about explorer and admin portal today on our main site in two new blogs. 

![Screenshot from 2021-12-08 09-35-49](https://user-images.githubusercontent.com/26298009/145167545-e7b9ca4c-0bfd-4a37-a45b-ddcf566efadc.png)

**Comment by ehab-hassan** [comment]
![favicon](https://user-images.githubusercontent.com/10484295/145174684-4967e176-de6c-4408-aa97-9d7164c2057d.png)
![favicon_white](https://user-images.githubusercontent.com/10484295/145174686-17a87fcc-f2b3-4a10-9b78-3a081e1520dd.png)

**Comment by MohamedElmdary** [comment]
### Updated

#### PR
https://github.com/threefoldtech/tfchain_portal/pull/22
