### ISSUE TITLE
Blocked on accepting T&C

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/tfchain_portal#33]
I reconnect to my account, I can't go forward because it's stuck at accepting the T&C (keeps on spinning)

<img width="1280" alt="Screenshot 2022-01-13 at 14 38 06" src="https://user-images.githubusercontent.com/30384423/149340947-39bd5798-7ea4-4c11-a9b6-0833e6eece71.png">

**Comment by DylanVerstraete** [comment]
Balance of user was to low, this will not occur for new users

**Comment by gmachtel** [comment]
Can be closed, thanks
