### ISSUE TITLE
No more view on farm info, only node info is available

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/tfchain_portal#34]
I access my farm on testnet (using portal.test.grid.tf) 

Trying to update public IP information in my farm but I can't find it, only node info is visible. 

<img width="1280" alt="Screenshot 2022-01-13 at 14 40 50" src="https://user-images.githubusercontent.com/30384423/149341501-3b02f647-e2c1-4648-b751-0d948dcecdbb.png">

**Comment by DylanVerstraete** [comment]
Shouldnt be an issue anymore
