### ISSUE TITLE
Node info inside the personalised portal is not correct

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/tfchain_portal#35]
I connect to my farm inside the portal on testnet (portal.test.grid.tf) 
Now I see the node info, but the info on what part of the resources is consumed is zero. 

<img width="1280" alt="Screenshot 2022-01-13 at 14 40 50" src="https://user-images.githubusercontent.com/30384423/149342203-3bce743c-ffa7-4b1c-b4c2-2bfc7e724446.png">

In the public portal, it shows consumption (and this is the correct view) : 
<img width="1280" alt="Screenshot 2022-01-13 at 14 48 14" src="https://user-images.githubusercontent.com/30384423/149342273-9eb657d4-e0d2-4458-85a9-dd3b042dd4c6.png">

**Comment by DylanVerstraete** [comment]
@gmachtel is this still an issue?

**Comment by gmachtel** [comment]
Unfortunately yes, in any case on testnet. 

Portal view: 
<img width="933" alt="Screenshot 2022-01-25 at 15 22 05" src="https://user-images.githubusercontent.com/30384423/150994561-8756a54b-e945-43c4-b5a3-9f0cf37492a2.png">

Explorer: 
<img width="1280" alt="Screenshot 2022-01-25 at 15 22 26" src="https://user-images.githubusercontent.com/30384423/150994670-2935f496-89d2-4fd6-ab4c-3a4d7e99b267.png">

**Comment by gmachtel** [comment]
No idea, for some reason it does not show on the public explorer. 
<img width="1280" alt="Screenshot 2022-01-25 at 16 43 05" src="https://user-images.githubusercontent.com/30384423/151009451-f99ead58-e54e-49d5-a0a8-2ca03f86e059.png">
