### ISSUE TITLE
Allow farmers to add a name to their nodes

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfchain_portal#37]
Feature request from a farmer: add a name field to the node view which farmers can set for each node.

After further consideration, I realize that this probably relies on one of two things:

1. Committing the name to TF Chain, which I'm not sure we want to do
2. Storing it in the user's browser, which means it won't persist across machines

**Comment by DylanVerstraete** [comment]
Hmm.. I rather not do this, this is not something that was specced and in the browser cache it seems pretty silly to do.

**Comment by scottyeager** [comment]
Understood. Could be an appropriate feature for a farming dashboard within the Connect app. For now, will suggest they make themselves a spreadsheet or something :slightly_smiling_face:
