### ISSUE TITLE
"Take me to bootstrap page" link points to https://dev.bootstrap.grid.tf/

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfchain_portal#38]
This applies to

- https://portal.grid.tf/
- https://portal.test.grid.tf/

I believe this should be https://v3.bootstrap.grid.tf/

**Comment by DylanVerstraete** [comment]
added https://github.com/threefoldtech/tfchain_portal/commit/ea32224112ea2caa96c962eb6411ec16f0d1f6bc

waiting on https://github.com/threefoldtech/tf_operations/issues/611
