### ISSUE TITLE
implement consistent dns names

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/tfchain_portal#4]
- https://explorer3.grid.tf
- https://explorer3_test.grid.tf
- https://explorer3_dev1.grid.tf
- https://tfchain_admin.grid.tf
- https://tfchain_admin_test.grid.tf
- https://tfchain_admin_dev1.grid.tf
- https://hub.grid.tf
- https://hub_test.grid.tf
- https://hub_dev1.grid.tf
- https://hub.grid.tf
- https://hub_test.grid.tf
- https://hub_dev1.grid.tf
- https://tfchain.grid.tf  (for access to tfchain, should be loadbalanced to at least 2)
- https://tfchain_test.grid.tf
- https://tfchain_dev1.grid.tf
- https://tfchain_graphql.grid.tf  (for access to tfchain, should be loadbalanced to at least 2)
- https://tfchain_graphql_test.grid.tf
- https://tfchain_graphql_dev1.grid.tf

if same services re-used ok to point to same dns

- anything missing, if yes contact kristof
- if anything running on non default port let me know

**Comment by xmonader** [comment]
closing as we agreed yesterday
