### ISSUE TITLE
failed to create a farm on testnet using portal 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_portal#48]
https://circles.threefold.me/project/test-tfgrid3/issue/193 

+ typo faild instead of failed.

**Comment by DylanVerstraete** [comment]
@xmonader Not sure how this is possible. Maybe the connection to the public on node on testnet was lost?

**Comment by DylanVerstraete** [comment]
Farm creation needs additional validation

**Comment by DylanVerstraete** [comment]
https://github.com/threefoldtech/tfchain_portal/commit/7cd70c6ddb5327410cf48ed4bea54860a49a5bf8
