### ISSUE TITLE
Nodes not loading on portal

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_portal#49]
Reports coming in yesterday about portal not loading nodes. 
![photo_2022-02-22 10 20 23](https://user-images.githubusercontent.com/31733464/155101778-860dcc2c-ef33-41a0-b8fc-0bb3c24d9eeb.jpeg)

**Comment by sabrinasadik** [comment]
New release needed:  https://github.com/threefoldtech/tf_operations/issues/700
portal will be updated

**Comment by DylanVerstraete** [comment]
Fixed in https://github.com/threefoldtech/tfchain_portal/commit/3d288aa12fb9ab26c51f457a743212d6cc05f80e
