### ISSUE TITLE
can we merge explorer in portal?

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/tfchain_portal#5]
so users only have 1 UI?

**Comment by DylanVerstraete** [comment]
The explorer is meant for user to "browse" capacity, also for outside users. This "portal" is meant for power users and farmers. But we can put a link to the capacity explorer or embed a webview.

**Comment by xmonader** [comment]
decided to be iframed within the portal.

**Comment by DylanVerstraete** [comment]
currently live on devnet https://portal.tfchain.dev.threefold.io/explorer
