### ISSUE TITLE
Nodes public config UI issue

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfchain_portal#51]
In your nodes list you can set the public config of a node.
![image](https://user-images.githubusercontent.com/88312671/157713443-dab6e8c6-4e9a-40b7-ac34-957a8427373d.png)
If you click on the globe icon of a node that does not have a config, everything looks fine.
![image](https://user-images.githubusercontent.com/88312671/157713610-539748b3-3a96-4e20-a181-ab8327c831a7.png)
Once you click on a node that has a config, that same config appears for all other nodes
![image](https://user-images.githubusercontent.com/88312671/157713733-6c8ab6cd-3f90-416a-813f-847bbe61cf70.png)

Reproduce:
List nodes in portal

- Click node without public config -> fields empty
- Click node with public config -> fields filled
- Click node without public config -> fields filled

**Comment by DylanVerstraete** [comment]
fixed in https://github.com/threefoldtech/tfchain_portal/commit/43ea7189dff57667a592216e04e08b8f710adf6e
