### ISSUE TITLE
Lost node list on testnet portal

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfchain_portal#75]
When navigating to farms, the one Freefarm was listed but the node list was empty.

Recently added a new farm for dedicated nodes. After 5 nodes where added to the farm, those did appear in the node list

![image](https://user-images.githubusercontent.com/88312671/166696564-5ff041b6-d516-407d-8ec3-f3240c46dafa.png)

**Comment by DylanVerstraete** [comment]
There is a problem in the portal when multiple farms are connected (data is not fetched properly)
