### ISSUE TITLE
Add multiple IPs to farm

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfchain_portal#98]
Some farmers need to add a large number of IP addresses to their farm. Currently this can only be done one by one. Propose to add a way to submit multiple IPs simultaneously. Typically these would be in a continuous block, so range based input would be useful.

**Comment by coesensbert** [comment]
Related: https://github.com/threefoldtech/tfgrid_dashboard/issues/105

**Comment by scottyeager** [comment]
Ah yes, I opened this before realizing this functionality would be migrating to the new dashboard. Probably no reason to keep this issue around.
